require: rubocop-rspec

# We are using default RuboCop settings.
# # We are writing beautiful code.
# # There is nothing to change here. At least now.
AllCops:
  TargetRubyVersion: 2.6
  DefaultFormatter: fuubar
  DisplayCopNames: true
  ExtraDetails: true
  Exclude:
    - rakelib/**/*.rake
  RSpec:
    Patterns:
      - '_spec.rb$'

# Ignore block length in DSLs using blocks extensively
Metrics/BlockLength:
  Exclude:
  # RSpec DSL
  - '**/*_spec.rb'
  - '**/spec/**/*.rb'
  # Rake DSL
  - '**/rakelib/**/*.rake'
  # Rubygems DSL
  - '**/*.gemspec'

Metrics/MethodLength:
  Exclude:
  # Rake DSL
  - rakelib/**/*.rake
  - lib/rake/**.rb
  # RSpec DSL
  - '**/spec/**/*.rb'

Metrics/ModuleLength:
  Exclude:
  # RSpec DSL
  - spec/**/*.rb

Metrics/AbcSize:
  Exclude:
  # Rake DSL
  - rakelib/**/*.rake
  # RSpec DSL
  - '**/spec/**/*.rb'
  # Rodauth configuration
  - lib/roda/plugins/authentication.rb

Metrics/LineLength:
  Max: 120

Style/Encoding:
  StyleGuide: '#utf-8'
  Enabled: when_needed<Paste>

Style/Documentation:
  Enabled: false
